[profile.default]
src = "src"
out = "out"
libs = ["lib", "../lib"]
solc = "0.8.20"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=../lib/forge-std/src/"
]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
